#!/bin/bash

HOST='127.0.0.1'  #-h
PORT='3306'       #-P
USER='root'       #-u
PASSWORD='1Fangle12#$' #-p
DB='urpcs'
INIT_SQL=(urpcs.sql urpcs1.sql)

array=()
function split(){
  split_ret=${1//=/ }
  count=0
  for e in $split_ret
  do 
    array[$count]=$e
    let count++
  done 
}

function init(){
    echo "init command"
    for arg in  ${INIT_SQL[@]}
    do 
       echo 111:$arg 
       cat $arg | mysql -u$USER -p$PASSWORD $DB
    done
}


for arg in $*
do 
  split $arg
  case ${array[0]} in
        -h)
          HOST=${array[1]}
          echo "replace host:"$HOST
        ;;
        -p)
          PASSWORD=${array[1]}
          echo "replace password:"$PASSWORD
        ;;
        -u)
          USER=${array[1]}
          echo "replace user:"$USER
        ;;
        -P)
          PORT=${array[1]}
          echo "replace port:"$ PORT
        ;;
        up)
          echo "up command"
        ;;
        init)
          init
        ;;
        *)
          echo "do not know:"${array[0]}
        ;;
  esac
done

